name: flutter_pro_architect  # This will be your command name
description: A global CLI tool to generate Clean Architecture for Flutter.
version: 1.0.0
homepage: https://github.com/razuahmed75/flutter_architecture

environment:
  sdk: '>=3.0.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  args: ^2.7.0